### ISSUE TITLE
Problem: downloadable datasets dream.train not found

### ISSUE THREAD

**Issue by Sgt-Bad** [ylabbe/robopose#4]
If I try to re-train the dream models I can’t seem to download them. 
Attached you can see the terminal output I get when trying to download. 
Do you have an answer for my issue?/ do you know why I’m unable to download them? 
Btw thanks for your fantastic project.

```
$ python -m robopose.scripts.download --datasets=dream.train
Setting OMP and MKL num threads to 1.
0:00:00.001091 - Copying robopose:zip_files/dream/synthetic/panda_synth_train_dr.zip to /home/********/robopose/local_data/downloads/panda_synth_train_dr.zip
2023-07-31 17:03:48 ERROR : Google drive root 'zip_files/dream/synthetic/panda_synth_train_dr.zip': error reading source root directory: directory not found
2023-07-31 17:03:48 ERROR : Attempt 1/3 failed with 1 errors and: directory not found
2023-07-31 17:03:49 ERROR : Google drive root 'zip_files/dream/synthetic/panda_synth_train_dr.zip': error reading source root directory: directory not found
2023-07-31 17:03:49 ERROR : Attempt 2/3 failed with 1 errors and: directory not found
2023-07-31 17:03:49 ERROR : Google drive root 'zip_files/dream/synthetic/panda_synth_train_dr.zip': error reading source root directory: directory not found
2023-07-31 17:03:49 ERROR : Attempt 3/3 failed with 1 errors and: directory not found
Transferred:              0 B / 0 B, -, 0 B/s, ETA -
Errors:                 1 (retrying may help)
Elapsed time:         3.3s
2023/07/31 17:03:49 Failed to copyto: directory not found
0:00:03.341509 - Extracting dataset panda_synth_train_dr.zip...
Traceback (most recent call last):
  File "/home/********/anaconda3/envs/robopose/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/********/anaconda3/envs/robopose/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/********/robopose/robopose/scripts/download.py", line 205, in <module>
    main()
  File "/home/********/robopose/robopose/scripts/download.py", line 79, in main
    download_dream_dataset(synt_or_real, ds_name)
  File "/home/********/robopose/robopose/scripts/download.py", line 33, in download_dream_dataset
    zipfile.ZipFile(DOWNLOAD_DIR / zip_name).extractall(LOCAL_DATA_DIR / 'dream_datasets' / real_or_synt)
  File "/home/********/anaconda3/envs/robopose/lib/python3.7/zipfile.py", line 1240, in __init__
    self.fp = io.open(file, filemode)
FileNotFoundError: [Errno 2] No such file or directory: '/home/********/robopose/local_data/downloads/panda_synth_train_dr.zip'
```

**Comment by yannlabb** [comment]
Can you try manual downloads from here ?
https://www.paris.inria.fr/archive_ylabbeprojectsdata/robopose/

**Comment by Sgt-Bad** [comment]
Thank you, the solution worked.
It appears that the following files are absent from the `/Robopose/zip_files/dream/synthetic` directory on Google Drive: `panda_synth_train_dr.zip`, `kuka_synth_train_dr.zip` and `baxter_synth_train_dr.zip`
